### ISSUE TITLE
Google Translate Service Error again

### ISSUE THREAD

**Issue by def00111** [bpierre/gtranslate#69]
#### What steps will reproduce the problem?
1. 
2. 
3. 

#### Could you describe us your platform?
* Firefox version: 
* Operating system:

**Comment by bpierre** [comment]
It looks like @tx9191 is working on it? https://github.com/tx9191/gtranslate/commit/ccd56438029b4f21d9446746686689d296b84367

**Comment by def00111** [comment]
glad it will be fixed :)

**Comment by farmazon3000** [comment]
Same here, waiting to be fixed... I hope you will not loose too many users because repeating errors like this.

**Comment by tx9191** [comment]
pull request created #70

**Comment by S3ndG** [comment]
I was wondering why there are so many problems like that with Google translate service.
Could you explain me?
Thanks :)

**Comment by bpierre** [comment]
Version 0.13.1 has been submitted and is waiting for approval. Thanks again @tx9191!

@S3ndG 

The reason is that Google closed the Google Translate API for third party software, except if you pay for it. gtranslate is currently using the non-official API, which changes whenever Google decides it’s necessary. The only thing we can do is to adapt as fast as possible when they change it.

I contacted Google to know if gtranslate could have an access to the API, but they never replied.

I plan to add the Bing translator service at some point (#36), which could mitigate the problem by allowing people to change the translation provider.
